version: "3.9"

services:

  paybybank:
    build:
      context: ./.dockerfiles
      args:
        GID: 1000
        UID: 1000
        APPLICATION_NAME: ${APPLICATION_NAME}
    container_name: ${APPLICATION_NAME}
    ports:
      - "80:80"
    networks:
      - paybybank_network
    volumes:
      - ./:/var/www/html

  paybybank_db:
    image: mariadb
    container_name: paybybank_db
    volumes:
      - paybybank_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      paybybank_network:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paybybank
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  paybybank_network:
    driver: "bridge"

volumes:
  paybybank_db_data: