version: "3.9"

services:

  pay_by_bank:
    build:
      context: ./.dockerfiles
      args:
        GID: ${GID}
        UID: ${UID}
        APPLICATION_NAME: ${APPLICATION_NAME}
    container_name: ${APPLICATION_NAME}
    ports:
      - "80:80"
    networks:
      - pay_by_bank_network
    volumes:
      - ./:/var/www/html

  paybybank_db:
    image: mariadb
    container_name: paybybank_db
    volumes:
      - paybybank_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      pay_by_bank_network:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paybybank
      MYSQL_USER: paybybank
      MYSQL_PASSWORD: paybybank

networks:
  pay_by_bank_network:
    driver: "bridge"

volumes:
  paybybank_db_data: