version: "3.9"

services:

  paybybank_web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - paybybank_fpm
    networks:
      - paybybank_network

  paybybank_fpm:
    build:
      context: ./.dockerfiles/phpfpm
      args:
        GID: 1000
        UID: 1000
        APPLICATION_NAME: ${APPLICATION_NAME}
    container_name: ${APPLICATION_NAME}
    networks:
      - paybybank_network
    volumes:
      - ./:/var/www/html

  paybybank_db:
    container_name: paybybankdb
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - paybybank_db_volume:/data/db
      - ./.dockerfiles/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - paybybank_network
    environment:
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}

networks:
  paybybank_network:
    driver: "bridge"

volumes:
  paybybank_db_volume:
